name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag first-try
    - name: Run the Docker image
      run: docker run -d -p 8080:8080 first-try
    - name: Test
      run: docker exec first-try python ./client.py
